### ISSUE TITLE
Support for share / send a email link

### ISSUE THREAD

**Issue by tomyo** [NigelOToole/share-url#1]
Nice project!

I was looking for something like this for the case of email links.
I love that in mobile, a email anchor opens the email client to send an email right away (with things like subject prefilled).
But on the desktop, the UX is bad, most user simply would prefer to copy the email, go to the Gmail tab, and create a new email from there, since they don't have an email client installed.

Do you think you'd be interested in including this use case in the project?

:)

**Comment by NigelOToole** [comment]
Thanks. Thats an interesting use case, you could add an email link like below and only display it on small screens. Not the most robust solution but trying to detect mobile is beyond the scope of the plugin. However the share API works on mobile which would include an email link.
<button class="share-url" data-share-action="mailto:" data-share-title-parameter="subject">Email</button>

Did you have any suggestions on how to implement this?

**Comment by tomyo** [comment]
You're right, might be overkill for this library.

I want to be able to copy the email on desktop click, and send email directly on mobile click (follow common anchor behavior)
